// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: set_revoke_rt.sql

package database

import (
	"context"
)

const setRevokeRefreshToken = `-- name: SetRevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE token = $1
`

func (q *Queries) SetRevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, setRevokeRefreshToken, token)
	return err
}
