### リセット管理者状態
POST http://localhost:8080/admin/reset
###
# Expecting status code: 200

### ユーザー作成
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}
###
# Expecting status code: 201
# Expecting JSON at .email to be equal to "saul@bettercall.com"

### ログインしてアクセストークン・リフレッシュトークン取得
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "saul@bettercall.com",
  "password": "123456"
}
###
# Expecting status code: 200
# @token = $.token
# @refresh_token = $.refresh_token

### Chirp 作成（リフレッシュトークンで試す → 401 になるはず）
POST http://localhost:8080/api/chirps
Authorization: Bearer {{refresh_token}}
Content-Type: application/json

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}
###
# Expecting status code: 401

### Chirp 作成（アクセストークンで成功）
POST http://localhost:8080/api/chirps
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "body": "Let’s just say I know a guy... who knows a guy... who knows another guy."
}
###
# Expecting status code: 201

### リフレッシュトークンでアクセストークン再発行
POST http://localhost:8080/api/refresh
Authorization: Bearer {{refresh_token}}
###
# Expecting status code: 200
# @token2 = $.token

### Chirp 作成（新しいアクセストークンで成功）
POST http://localhost:8080/api/chirps
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "body": "I'm the guy who's gonna win you this case."
}
###
# Expecting status code: 201

### リフレッシュトークン無効化（ログアウト）
POST http://localhost:8080/api/revoke
Authorization: Bearer {{refresh_token}}
###
# Expecting status code: 204

### リフレッシュトークンでアクセストークン再発行 → 失敗
POST http://localhost:8080/api/refresh
Authorization: Bearer {{refresh_token}}
###
# Expecting status code: 401
